# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
    - staging
    - develop
    tags:
    - v1.*
  pull_request:
    branches:
    - master
    - staging
    - develop
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" workflow
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0' # The Go version to download (if necessary) and use.
    
    # Run build of the application
    - name: Run build
      run: go build main.go
      
    # Chmod binary
    - name: chmod binary
      run: chmod +x main

    # Persist the artifact
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: main-binary
        path: main

    # Install all the dependencies
    #- name: Install dependencies
    #  run: |
    #    go version
    #    go get -u golang.org/x/lint/golint
        
    # Run vet & lint on the code
    #- name: Run vet & lint
    #  run: |
    #    go vet .
    #    golint .
    
    # Run testing on the code
    #- name: Run testing
    #  run: cd test && go test -v
    
  # The "deploy" workflow
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [build] # Only run this workflow when "build" workflow succeeds
    #if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} # Only run this workflow if it is master branch on push event
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v2

    # Download build artifact
    - name: Download main binary
      uses: actions/download-artifact@v2
      with:
        name: main-binary

    # Deploy to Docker registry
    - name: Deploy to Docker registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: junior158/helloapp
        tag_with_ref: true
